server:
  port: 8081

spring:
  application:
    name: contract-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 70MB
      max-request-size: 70MB

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/procuremind_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Automatically creates tables for Day 1 testing
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Kafka Producer Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: contract-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "com.procuremind.*"
  # Disable Flyway for Day 1 testing
  flyway:
    enabled: true

# Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html